package handlers

import (
	"bytes"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/ARS-caffanap/octo-pos/backend/internal/config"
	"github.com/ARS-caffanap/octo-pos/backend/internal/database"
	"github.com/ARS-caffanap/octo-pos/backend/internal/models"
	"github.com/gin-gonic/gin"
	"github.com/golang-jwt/jwt/v5"
	"golang.org/x/crypto/bcrypt"
)

// setupAuthTest creates a Gin engine with the auth handler wired up,
// using a nil DB (safe for validation-only tests that never hit the DB).
func setupAuthTest() (*gin.Engine, *config.Config) {
	gin.SetMode(gin.TestMode)

	cfg := &config.Config{
		JWTSecret: "test-secret-key-for-unit-tests",
	}

	// nil DB — validation errors abort before FindByEmail is called.
	userRepo := database.NewUserRepo(nil)
	authHandler := NewAuthHandler(cfg, userRepo)

	r := gin.New()
	r.POST("/api/auth/login", authHandler.Login)

	return r, cfg
}

func TestLogin_MissingFields(t *testing.T) {
	r, _ := setupAuthTest()

	tests := []struct {
		name string
		body interface{}
	}{
		{"empty body", gin.H{}},
		{"missing password", gin.H{"email": "test@example.com"}},
		{"missing email", gin.H{"password": "password123"}},
		{"invalid email", gin.H{"email": "not-an-email", "password": "password123"}},
		{"short password", gin.H{"email": "test@example.com", "password": "12345"}},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			b, _ := json.Marshal(tt.body)
			req, _ := http.NewRequest("POST", "/api/auth/login", bytes.NewReader(b))
			req.Header.Set("Content-Type", "application/json")
			w := httptest.NewRecorder()
			r.ServeHTTP(w, req)

			if w.Code != http.StatusUnauthorized {
				t.Errorf("expected 401, got %d", w.Code)
			}
		})
	}
}

func TestLogin_ConfigSetup(t *testing.T) {
	// Verify the test config is wired correctly.
	_, cfg := setupAuthTest()
	if cfg.JWTSecret != "test-secret-key-for-unit-tests" {
		t.Error("JWT secret not set correctly in test config")
	}
}

func TestLoginResponse_Shape(t *testing.T) {
	// Verify the LoginResponse JSON shape matches what the frontend expects.
	resp := models.LoginResponse{
		AccessToken: "eyJhbG...9ftE",
		TokenType:   "Bearer",
		ExpiresIn:   86400,
		User: models.UserInfo{
			ID:       "user-123",
			Email:    "admin@example.com",
			Role:     "admin",
			TenantID: "tenant-456",
		},
	}
	b, _ := json.Marshal(resp)

	var parsed map[string]interface{}
	if err := json.Unmarshal(b, &parsed); err != nil {
		t.Fatalf("failed to parse LoginResponse JSON: %v", err)
	}

	if _, ok := parsed["access_token"]; !ok {
		t.Errorf("LoginResponse missing 'access_token' field: %s", string(b))
	}
	if parsed["token_type"] != "Bearer" {
		t.Errorf("expected token_type='Bearer', got %v", parsed["token_type"])
	}
	if parsed["expires_in"] != float64(86400) {
		t.Errorf("expected expires_in=86400, got %v", parsed["expires_in"])
	}
	user, ok := parsed["user"].(map[string]interface{})
	if !ok {
		t.Fatalf("LoginResponse missing or invalid 'user' field: %s", string(b))
	}
	if user["id"] != "user-123" {
		t.Errorf("expected user.id='user-123', got %v", user["id"])
	}
	if user["email"] != "admin@example.com" {
		t.Errorf("expected user.email='admin@example.com', got %v", user["email"])
	}
	if user["role"] != "admin" {
		t.Errorf("expected user.role='admin', got %v", user["role"])
	}
	if user["tenant_id"] != "tenant-456" {
		t.Errorf("expected user.tenant_id='tenant-456', got %v", user["tenant_id"])
	}
}

func TestAuthErrorResponse_Shape(t *testing.T) {
	resp := models.AuthErrorResponse{Error: "unauthorized", Message: "invalid email or password"}
	b, _ := json.Marshal(resp)

	var parsed map[string]interface{}
	if err := json.Unmarshal(b, &parsed); err != nil {
		t.Fatalf("failed to parse AuthErrorResponse JSON: %v", err)
	}

	if parsed["error"] != "unauthorized" {
		t.Errorf("expected error='unauthorized', got %v", parsed["error"])
	}
	if parsed["message"] != "invalid email or password" {
		t.Errorf("expected message='invalid email or password', got %v", parsed["message"])
	}
}

func TestAuthErrorResponse_WithRetryAfter(t *testing.T) {
	resp := models.AuthErrorResponse{
		Error:      "too_many_attempts",
		Message:    "too many login attempts",
		RetryAfter: 300,
	}
	b, _ := json.Marshal(resp)

	var parsed map[string]interface{}
	if err := json.Unmarshal(b, &parsed); err != nil {
		t.Fatalf("failed to parse AuthErrorResponse JSON: %v", err)
	}

	if parsed["retry_after"] != float64(300) {
		t.Errorf("expected retry_after=300, got %v", parsed["retry_after"])
	}
}

func TestJWTClaims_Compatibility(t *testing.T) {
	// Verify that tokens generated by the handler are compatible with
	// middleware.JWTAuth (same signing method, same claims format).
	cfg := &config.Config{JWTSecret: "test-secret"}

	claims := jwt.MapClaims{
		"tenant_id": "tenant-123",
		"user_id":   "user-456",
		"role":      "admin",
		"email":     "admin@example.com",
		"iat":       1700000000,
		"exp":       1800000000,
	}

	token := jwt.NewWithClaims(jwt.SigningMethodHS256, claims)
	signed, err := token.SignedString([]byte(cfg.JWTSecret))
	if err != nil {
		t.Fatalf("failed to sign token: %v", err)
	}

	// Parse it back with the middleware's logic
	parsed, err := jwt.Parse(signed, func(t *jwt.Token) (interface{}, error) {
		if _, ok := t.Method.(*jwt.SigningMethodHMAC); !ok {
			return nil, jwt.ErrSignatureInvalid
		}
		return []byte(cfg.JWTSecret), nil
	})
	if err != nil {
		t.Fatalf("failed to parse token: %v", err)
	}
	if !parsed.Valid {
		t.Fatal("token should be valid")
	}

	pc, ok := parsed.Claims.(jwt.MapClaims)
	if !ok {
		t.Fatal("claims should be MapClaims")
	}
	if pc["tenant_id"] != "tenant-123" {
		t.Errorf("tenant_id: expected 'tenant-123', got %v", pc["tenant_id"])
	}
	if pc["user_id"] != "user-456" {
		t.Errorf("user_id: expected 'user-456', got %v", pc["user_id"])
	}
	if pc["role"] != "admin" {
		t.Errorf("role: expected 'admin', got %v", pc["role"])
	}
}

func TestBcryptPasswordFlow(t *testing.T) {
	// Verify the bcrypt flow: hash a password, then compare.
	password := "admin123"
	hash, err := bcrypt.GenerateFromPassword([]byte(password), bcrypt.DefaultCost)
	if err != nil {
		t.Fatalf("bcrypt generate: %v", err)
	}

	if err := bcrypt.CompareHashAndPassword(hash, []byte(password)); err != nil {
		t.Errorf("bcrypt compare should succeed for correct password: %v", err)
	}

	if err := bcrypt.CompareHashAndPassword(hash, []byte("wrongpassword")); err == nil {
		t.Error("bcrypt compare should fail for wrong password")
	}
}

// TestLogin_EmailRateLimit verifies that after pre-exhausting the email limiter,
// the handler returns 429 with retry_after before hitting the DB.
func TestLogin_EmailRateLimit(t *testing.T) {
	gin.SetMode(gin.TestMode)

	cfg := &config.Config{JWTSecret: "test-secret"}
	userRepo := database.NewUserRepo(nil) // won't be reached because rate limit fires first
	authHandler := NewAuthHandler(cfg, userRepo)

	// Pre-exhaust the email limiter by calling Allow() 5 times directly.
	for i := 0; i < 5; i++ {
		allowed, _ := authHandler.emailLimiter.Allow("admin@octopos.local")
		if !allowed && i < 5 {
			t.Fatalf("email limiter blocked prematurely at attempt %d", i+1)
		}
	}

	r := gin.New()
	r.POST("/api/auth/login", authHandler.Login)

	// Now the 6th call through the handler should be 429.
	b, _ := json.Marshal(gin.H{"email": "admin@octopos.local", "password": "wrongpassword"})
	req, _ := http.NewRequest("POST", "/api/auth/login", bytes.NewReader(b))
	req.Header.Set("Content-Type", "application/json")
	w := httptest.NewRecorder()
	r.ServeHTTP(w, req)

	if w.Code != http.StatusTooManyRequests {
		t.Errorf("expected 429, got %d", w.Code)
	}

	var parsed map[string]interface{}
	if err := json.Unmarshal(w.Body.Bytes(), &parsed); err != nil {
		t.Fatalf("failed to parse 429 response: %v", err)
	}
	if parsed["error"] != "too_many_attempts" {
		t.Errorf("expected error='too_many_attempts', got %v", parsed["error"])
	}
	if _, ok := parsed["retry_after"]; !ok {
		t.Error("429 response missing 'retry_after' field")
	}
	if w.Header().Get("Retry-After") == "" {
		t.Error("429 response missing 'Retry-After' header")
	}
}

// TestLogin_IPRateLimit verifies that after pre-exhausting the IP limiter,
// the handler returns 429 before hitting the email limiter or DB.
func TestLogin_IPRateLimit(t *testing.T) {
	gin.SetMode(gin.TestMode)

	cfg := &config.Config{JWTSecret: "test-secret"}
	userRepo := database.NewUserRepo(nil)
	authHandler := NewAuthHandler(cfg, userRepo)

	// Pre-exhaust the IP limiter for "192.0.2.1".
	for i := 0; i < 20; i++ {
		allowed, _ := authHandler.ipLimiter.Allow("192.0.2.1")
		if !allowed && i < 20 {
			t.Fatalf("IP limiter blocked prematurely at attempt %d", i+1)
		}
	}

	r := gin.New()
	r.POST("/api/auth/login", authHandler.Login)

	b, _ := json.Marshal(gin.H{"email": "someone@test.local", "password": "wrong123"})
	req, _ := http.NewRequest("POST", "/api/auth/login", bytes.NewReader(b))
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("X-Forwarded-For", "192.0.2.1")
	req.RemoteAddr = "192.0.2.1:1234"
	w := httptest.NewRecorder()
	r.ServeHTTP(w, req)

	if w.Code != http.StatusTooManyRequests {
		t.Errorf("expected 429, got %d", w.Code)
	}

	var parsed map[string]interface{}
	if err := json.Unmarshal(w.Body.Bytes(), &parsed); err != nil {
		t.Fatalf("failed to parse 429 response: %v", err)
	}
	if parsed["error"] != "too_many_attempts" {
		t.Errorf("expected error='too_many_attempts', got %v", parsed["error"])
	}
	if _, ok := parsed["retry_after"]; !ok {
		t.Error("429 response missing 'retry_after' field")
	}
	if w.Header().Get("Retry-After") == "" {
		t.Error("429 response missing 'Retry-After' header")
	}
}
